version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      # hostpath:containerpath

  site:
    build:
      context: ./site.dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes: 
      - /mnt:/mnt
    # hostpath:containerpath